---
- hosts: all
  vars:
    target: /opt/happyman
  tasks:
    - pkgng: name=py27-virtualenv state=present
    - git: repo=https://github.com/skyshaper/happyman.git dest={{ target }}
    - command: virtualenv {{target}}/python/virtualenv creates={{ target }}/python/virtualenv
    - file: path={{target}}/local.new state=absent
    - pkgng: name=p5-carton state=present
    - pkgng: name=p5-Getopt-Long state=present
    - command: "carton install --without develop,test --path local.new chdir={{ target }}"
    - file: path={{target}}/local state=absent
    - command: "mv {{target}}/local.new {{target}}/local"
    - command: "{{ target }}/python/virtualenv/bin/pip install --no-index --find-links={{ target }}/python/vendor/cache/ -r {{ target }}/python/requirements_lock.txt"
    - command: service happyman restart
