#!/usr/bin/env perl
use v5.14;
use warnings;
use lib qw(lib local/lib/perl5);

use App::Happyman::Connection;
use File::Slurp;
use Mojo::JSON;

my $json = Mojo::JSON->new;
my $conf = $json->decode( scalar read_file('happyman.conf') );
if ( !$conf ) {
    die 'Failed to parse config: ' . $json->error . "\n";
}
my $conn = App::Happyman::Connection->new( $conf->{connection} );

while ( my ( $plugin_name, $plugin_conf ) = each $conf->{plugins} ) {
    $conn->load_plugin( $plugin_name, $plugin_conf );
}

$conn->run_forever();
