#!/bin/sh -e
curl -L http://cpanmin.us | perl - App::cpanminus
cpanm Carton
carton install --cached
virtualenv python_virtualenv
./python_virtualenv/bin/pip install --no-index --find-links=vendor/python_cache/ -r cobe_python_requirements_lock.txt