#!/bin/sh -e
cpanm --notest --local-lib local List::Util
cpanm --installdeps --notest --with-develop --local-lib local .
virtualenv python/virtualenv

# Work around “clang: error: unknown argument: '-mno-fused-madd'”
export CFLAGS=-Qunused-arguments
export CPPFLAGS=-Qunused-arguments

./python/virtualenv/bin/pip install --allow-all-external --allow-unverified python-irclib -r python/requirements.txt