#!/bin/sh -ex
rm -rf local vendor/bundle
carton update
carton bundle
if git diff --quiet --exit-code; then
    exit 0
fi
./python/virtualenv/bin/pip install --upgrade -r ./python/requirements.txt
./python/virtualenv/bin/pip freeze > ./python/requirements_lock.txt
./python/virtualenv/bin/pip install --download=python/vendor/cache/ -r ./python/requirements_lock.txt
./script/test
git add -A
git commit -m "Update dependencies" || exit 0 
git push
ansible-playbook -i ansible_hosts -c local ansible_playbook.yml
exit 1
