#!/bin/sh -e
apt-get update 
apt-get -y dist-upgrade 
vmware-config-tools.pl -d

apt-get install -y build-essential wget
cd /tmp && wget http://www.cpan.org/src/5.0/perl-5.18.1.tar.gz && tar xf perl-5.18.1.tar.gz
cd /tmp/perl-5.18.1 && ./Configure -des && make && make install

apt-get install -y python python-dev python-setuptools
easy_install virtualenv
apt-get install -y libssl-dev openssl

apt-get install -y ngircd curl
curl -L http://cpanmin.us | sudo perl - App::cpanminus
sudo cpanm Carton
