- hosts: all
  roles:
    - common
- hosts: development
  tasks:
    - name: install test ircd
      apt: pkg=ngircd
    - include: happyman.yml application_directory=/vagrant cpanm_with_develop=yes
- hosts: production
  roles:
    - nginx
  tasks:
    - name: install supervisor
      apt: pkg={{item}}
      with_items:
        - supervisor
    - name: configure nginx proxy to happyman
      copy:
        src=files/etc/nginx/sites-available/happyman
        dest=/etc/nginx/sites-available/happyman
      notify:
        - reload nginx
    - name: enable nginx proxy to happyman
      file:
        path=/etc/nginx/sites-enabled/happyman
        src=/etc/nginx/sites-available/happyman
        state=link
      notify:
        - reload nginx
    - name: get code
      git: repo=https://github.com/skyshaper/happyman.git dest=/opt/happyman
    - include: happyman.yml application_directory=/opt/happyman
    - name: create happyman user
      user: name=happyman system=yes home=/opt/happyman createhome=no shell=/bin/zsh
    - copy: create supervisor config
      copy: src=files/supervisor/happyman.conf dest=/etc/supervisor/conf.d/happyman.conf
    - copy: create happyman config
      copy: src=files/happyman.conf dest=/opt/happyman/happyman.conf
    - name: restart
      supervisorctl: name=happyman state=restarted
